---
apiVersion: v1
kind: Service
metadata:
  namespace: monitoring
  name: prometheus-service
  labels:
    prometheus: main
spec:
  type: NodePort
  ports:
    - name: prometheus-service
      port: 9090
      targetPort: 9090
      protocol: TCP
  selector:
    prometheus: main
