apiVersion: v1
kind: Service
metadata:
  name: simple-webapp-color-service
spec:
  type: NodePort
  ports:
  - targetPort: 8080
    port: 8080
    nodePort: 30038
  selector:
    app: simple-webapp-color
    type: frontend
